version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /tmp/word-service:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d/