server:
  port: 8081

# jdbc
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  username: max
  password: password
  word-service:
    url: jdbc:mysql://localhost:3306/cenylcz?serverTimezone=UTC&useSSL=false&autoReconnect=true

# kafka
kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: word-group

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      expose: ["health", "info"]
      exposure:
        incluse: ["*"]
      base-path: "/manage"
    health:
      diskspace:
        enabled: false